### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by viktorsmari** [dyne/valueflows-dashboard#1]
Hi @ivanminutillo 

1. Can you quickly document how to start and run the project?
2. Which node version? Can you add a `.nvmrc` ?

After cloning and doing `npm i` and `npm run start` the project it did not start.

When it finally started after manually installing `react-scripts` I got this error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1218:7)
    at noopServiceWorkerMiddleware (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/index.js:317:13)
    at /home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/index.js:335:12)
    at next (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/viktor/fablab/reflow/valueflows-dashboard/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by ivanminutillo** [comment]
Hi @viktorsmari
you need to connect it to the backend, that currently is available here:
https://github.com/dyne/clj-flows
things can break and change soon, as they're both at prototype level, and particularly this frontend was created *only* to showcase the idea during the amsterdam workshop.
More about the workshop here:
https://reflowproject.eu/blog/dev-diary-our-journey-towards-the-reflowos/
